default.nix: disable python's shellHook
  Running setup.py develop for nixpkgs-review
    ERROR: Command errored out with exit status 1:
     command: /nix/store/aw85aijllnc5spk2fqbivygrhx6x7411-python3-3.7.6/bin/python3.7 -c 'import sys, setuptools, tokenize; sys
.argv[0] = '"'"'/home/joerg/git/nixpkgs-review/setup.py'"'"'; __file__='"'"'/home/joerg/git/nixpkgs-review/setup.py'"'"';f=geta
ttr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code,
__file__, '"'"'exec'"'"'))' develop --no-deps --prefix=/run/user/1000/tmp.DzvCDdp9wW
         cwd: /home/joerg/git/nixpkgs-review/
    Complete output (33 lines):
    running develop
    Checking .pth file support in /run/user/1000/tmp.DzvCDdp9wW/lib/python3.7/site-packages
    /nix/store/aw85aijllnc5spk2fqbivygrhx6x7411-python3-3.7.6/bin/python3.7 -E -c pass
    TEST FAILED: /run/user/1000/tmp.DzvCDdp9wW/lib/python3.7/site-packages does NOT support .pth files
    error: bad install directory or PYTHONPATH

    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /run/user/1000/tmp.DzvCDdp9wW/lib/python3.7/site-packages

    and your PYTHONPATH environment variable currently contains:

        '/run/user/1000/pip-build-env-b4t7o_fs/site'